### PR TITLE
More welcoming phrasing in the readme

### PR DESCRIPTION
**Pull request by skatenerd**

### CODE REVIEW

**Comment by iostreamer-X** [comment]
I am sorry @skatenerd I am afraid I can't do that 😆

**Comment by adrianbw** [comment]
May I ask why?

**Comment by iostreamer-X** [comment]
@adrianbw I thought @skatenerd was messing around. I didn't know it bothered people. 
Changing it right away.

Cheers!

**Comment by adrianbw** [comment]
Thank you!

**Comment by skatenerd** [comment]
It's worth noting that the same language still appears in the project tagline:

image

**Comment by iostreamer-X** [comment]
Oh! I must have missed that. It's changed now. Thanks for pointing it out.

**Comment by adrianbw** [comment]
Hey, let me just say that I really appreciate your willingness to fix this stuff. Thanks for that, and for making FuncShell. 🙇

**Pull request merged**
